### ISSUE TITLE
<Tag> Error

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/cd-read-more-changelog#1]
This component does not play well with Rich Text Editors like the ones found in Shopify. Ideally, the RTE needs to be able to insert multiple `<p><br><a><strong>` tags, etc. But you can see from the screenshot in the one instance it applies the `class=js-read-more__ellipsis is-hidden` to even the break-tags. Ideally, the JS code would wrap everything in a div, so you could put `<p><br><a><strong>` tags inside of it when needed without creating multiple instances of the "Read More" button.

How can the JS be altered to account for RTE's?

<img width="580" alt="Screen Shot 2021-08-30 at 9 07 02 PM" src="https://user-images.githubusercontent.com/6481954/131440726-d473bb8b-be56-428f-bbdc-0a5fe89a5179.png">

**Comment by claudia-romano** [comment]
Hi there, if you are using a RTE, then you should use the [Manual content truncation option](https://codyhouse.co/ds/components/info/read-more#manual-truncation), rather than the [max number of characters option](https://codyhouse.co/ds/components/info/read-more#max-char) as it seems you are doing. 

Let's say you have a `<span>` and the content is truncated in the middle of the `<span>`, then the plugin should create an additional closing/opening span tag but this could affect the layout (e.g., color, margin of the text, etc).

Using the Manual content truncation option should fix the issue you are experiencing. Let me know if you have any doubts!

**Comment by claudia-romano** [comment]
Hi there, I'm closing this issue since no additional info was provided. Feel free to reopen it if you are still having problems. Cheers!
